# v0.1 – CV-Parser contract
type: object
required:
  - meta
  - candidate
  - sections
properties:
  meta:
    type: object
    required: [checksum, parsed_at, file_name, page_count, parser_version]
    properties:
      checksum:        {type: string}          
      parsed_at:       {type: string, format: date-time}
      file_name:       {type: string}
      page_count:      {type: integer, minimum: 1}
      parser_version:  {type: string}
  candidate:
    type: object
    required: [full_name, contact]
    properties:
      full_name: {type: string}
      contact:
        type: object
        required: [email, phone]
        properties:
          email:     {type: string}
          phone:     {type: string}            
          location:  {type: string}
          linkedin:  {type: string}
          github:    {type: string}
      summary:   {type: string}
  sections:
    type: object
    required: [experience, education, skills]
    properties:
      experience:
        type: array
        items:
          type: object
          required: [title, employer, start_date]
          properties:
            title:       {type: string}
            employer:    {type: string}
            location:    {type: string}
            start_date:  {type: string, pattern: "^[0-9]{4}-[0-9]{2}$"}  
            end_date:    {type: string}
            bullets:     {type: array, items: {type: string}}
      education:
        type: array
        items:
          type: object
          required: [title, employer, start_date]
          properties:
            title:       {type: string}
            employer:    {type: string}
            location:    {type: string}
            start_date:  {type: string, pattern: "^[0-9]{4}-[0-9]{2}$"}
            end_date:    {type: string}
      skills:
        type: object
        required: [hard]
        properties:
          hard: {type: array, items: {type: string}}
          soft: {type: array, items: {type: string}}
      certifications: {type: array, items: {type: string}}
      languages:
        type: array
        items:
          type: object
          required: [name, level]
          properties:
            name:  {type: string}
            level: {type: string}
      awards: {type: array, items: {type: string}}
  parser_notes:
    type: array
    items: {type: string}
  media_refs:
    type: array
    items:
      type: object
      required: [page, bbox, type, file]
      properties:
        page: {type: integer}
        bbox: {type: array, minItems: 4, maxItems: 4, items: {type: number}}
        type: {type: string}
        file: {type: string}
  target_role: {type: string}
additionalProperties: false
